name: TestLinter

on:
  - push:
  - pull-request:

env:
  CI: true

jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: make install
      - run: make lint
